# Generated by Django 6.0.1 on 2026-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0003_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
