# Generated by Django 6.0.2 on 2026-04-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_app.account'),
        ),
    ]
